# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcl < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.8.0-beta.1"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0-beta.1/kcl-v0.8.0-beta.1-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "55396e0f5109568a053862005eb2b4eb4e771164bca0e2f6a98d5845931030dd"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0-beta.1/kcl-v0.8.0-beta.1-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1e134c773631498e6f0218fbe25abdf77c57c48efd4ec884d74c7456ee99ec70"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0-beta.1/kcl-v0.8.0-beta.1-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "94706a078c642e8bab902554ea79e7ab7d1e685985c8dccaaa55928bc480f252"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0-beta.1/kcl-v0.8.0-beta.1-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1931488fa9052095d3c266ab34cdedf4381bff288312df630aa557bd4de49348"

      def install
        bin.install "kcl"
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
