# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT0100 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.10.0-rc.1"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    on_intel do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-rc.1/kcl-v0.10.0-rc.1-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f031a52802e527a2dea7cc82bdc8bd2974a08ebf039b6cccde7076b4afb2729"

      def install
        bin.install "kcl"
      end
    end
    on_arm do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-rc.1/kcl-v0.10.0-rc.1-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4a7fc78198c76f2fea46f6e6ec9a6208cfa26d62804b1bbab8c956d7e2862dc8"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-rc.1/kcl-v0.10.0-rc.1-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "1be7e5b33fac299e935a04213d01f09edae6f902bedda6b4b95adb357c9c75d1"

        def install
          bin.install "kcl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-rc.1/kcl-v0.10.0-rc.1-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f7e50b0b1d65cf5346116184e5f661d343fd3cdb0472e737105755efb7fe03d6"

        def install
          bin.install "kcl"
        end
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
