# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT070 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.7.0-beta.1"
  license "Apache License"

  depends_on "kcl-lsp@0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.0-beta.1/kcl-v0.7.0-beta.1-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c058ad822df2e55508e9306762e45b3a835153ac5b5e900825fdcd49b38bc59f"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.0-beta.1/kcl-v0.7.0-beta.1-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0395bf51f2fac90356446b2b75e56f067b7d71c5647afce231a385785b431c7a"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.0-beta.1/kcl-v0.7.0-beta.1-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f4413fc5408f108a7b9d4f351e66711d1e01b3b2ed5ef1055624d46eccab3c17"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.0-beta.1/kcl-v0.7.0-beta.1-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c4082da4341c8043ea43a3a869bb6430b46fb4328138b98fecaa4d5f826d795"

      def install
        bin.install "kcl"
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
