# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT010 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.10.8"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    on_intel do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.8/kcl-v0.10.8-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c86c92076003c36c7a46a8b21fa885085384b6c98ac92fcb302738656051b75f"

      def install
        bin.install "kcl"
      end
    end
    on_arm do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.8/kcl-v0.10.8-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7252e8373bda2941ab0806f55dd2c8c3e2a988c82fa586c4377d341fb2b8c8ee"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.8/kcl-v0.10.8-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "7544ab9e6cee96b7e479f963f0f80785e1c7496c499d6ea98ba1d82e0226366d"

        def install
          bin.install "kcl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.8/kcl-v0.10.8-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "5b8cf956b4378da63737261dd59d737f209fd7947371fc76a68709af107d0895"

        def install
          bin.install "kcl"
        end
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
