# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT010 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.10.6"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    on_intel do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.6/kcl-v0.10.6-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "fbc0fe397fe9e94fa04b5780ca44310b8d8c191ac7fb5dc94ef440928687ed72"

      def install
        bin.install "kcl"
      end
    end
    on_arm do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.6/kcl-v0.10.6-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e5e3f546bcc06d244718770fa625ddf18f395648c0f2d4d7279b8a0625ac241a"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.6/kcl-v0.10.6-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "9f3f194cfa5bdd00b9fb7df48d94b9390763c8cce13841e9f48c6ab090c497aa"

        def install
          bin.install "kcl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.6/kcl-v0.10.6-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d7196808b49b0bf2512b41d3a96a475b683ebf7e9663c071c627f644cff252c9"

        def install
          bin.install "kcl"
        end
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
