# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT090 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.9.0-alpha.1"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    on_intel do
      url "https://github.com/kcl-lang/cli/releases/download/v0.9.0-alpha.1/kcl-v0.9.0-alpha.1-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "73ca870c19583c158581a09c838c054f4466018d92a3191db2440a1496edc622"

      def install
        bin.install "kcl"
      end
    end
    on_arm do
      url "https://github.com/kcl-lang/cli/releases/download/v0.9.0-alpha.1/kcl-v0.9.0-alpha.1-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "838515ec9b2a19f061f82cc7c18e7806a2db1897acae576ca8f62e91ac6e051a"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.9.0-alpha.1/kcl-v0.9.0-alpha.1-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "9be08527f8f32e7cf8911eb897d7c72dca3f31f419bc4c6fe34a9e9a1ee763b6"

        def install
          bin.install "kcl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.9.0-alpha.1/kcl-v0.9.0-alpha.1-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f778cb53cbe8cd2a08e2a6d34ff9dea7e45aca5598c017fca1c4ff90821efae8"

        def install
          bin.install "kcl"
        end
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
