# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT080 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.8.0"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0/kcl-v0.8.0-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "97891cf40fe3a895fdfed9bc7a2fab4a157a86462073576b909681bf7f27c8a8"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0/kcl-v0.8.0-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "dc94ed733e6b47255ed36757de31a979bbf86a4e9339904654c090ca7a105a60"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0/kcl-v0.8.0-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0fb33ddce32614d73dd6982c6245d41c91ba0594037ce3ea72781c1daa124f49"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.8.0/kcl-v0.8.0-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c484960af43fbf24f6d971f5a347ec2b2eaec04056c92e3b0f8b5014f06a631a"

      def install
        bin.install "kcl"
      end
    end
  end
  
    test do
      system "#{bin}/kcl version"
    end
  end
