# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT074 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.7.4"
  license "Apache License"

  depends_on "kcl-lsp@0.7.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.4/kcl-v0.7.4-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d33bdb7ec63c53fc3319011e9626c0505647405c22c2a1851351e975d9d41ea1"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.4/kcl-v0.7.4-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "9368b4c72c139404d9a1449eb02ccebac724391d69592caf9b9e8d4cea45191b"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.4/kcl-v0.7.4-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "65f9ce863465600237d6117a11e16d5ced1567ccdf74563cad7d5a64dadc5988"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.4/kcl-v0.7.4-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5c9b12bf3c62fcc092e7438c021d3b0dd5fc5e91b0c304b45f0c807ac5d4509a"

      def install
        bin.install "kcl"
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
