# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT073 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.7.3"
  license "Apache License"

  depends_on "kcl-lsp@0.7.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.3/kcl-v0.7.3-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2746e6f5ad850af49b9f9a66cd50670972f0c6823e22d383aff447b518860fcf"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.3/kcl-v0.7.3-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4a256800c77e098359400b12d6db0a3060c8631ad90b7b90212909986578c7f"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.3/kcl-v0.7.3-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e51528d02e3e31ffa908345da11ee05d9e270744196d3055713f4489d63cf794"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.7.3/kcl-v0.7.3-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0774b0f808f949313b5b90aeb92983fc7c6d05ef2a6f838d3817e3838bd84494"

      def install
        bin.install "kcl"
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
