# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclAT090 < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.10.0-beta.1"
  license "Apache License"

  depends_on "kcl-lsp"

  on_macos do
    on_intel do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-beta.1/kcl-v0.10.0-beta.1-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f2fabae4a7347b1f75f17db9b7c944fcc0313480356ef187aa36b79401e33cb0"

      def install
        bin.install "kcl"
      end
    end
    on_arm do
      url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-beta.1/kcl-v0.10.0-beta.1-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ad66a36a079e9db8ffe110fbc0827914b537d2995dcdf4c0fac98133ebfb734c"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-beta.1/kcl-v0.10.0-beta.1-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "50ac8cc2a0e0ccb7199c1f25eb42339c45b26558a279afaffb4c92f70208d299"

        def install
          bin.install "kcl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kcl-lang/cli/releases/download/v0.10.0-beta.1/kcl-v0.10.0-beta.1-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "75421b9a4b24a04324bef28d616fba95cbb5e3cb119293f6e778c7fd5ee3763e"

        def install
          bin.install "kcl"
        end
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
