# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcl < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.12.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.6/kcl-v0.12.6-darwin-amd64.tar.gz"
      sha256 "87611a5bca34b958c9788c6a9a755a601294a05a0bf60ec0d7a9d9cded68c4ad"

      define_method(:install) do
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.6/kcl-v0.12.6-darwin-arm64.tar.gz"
      sha256 "41dfe89c0af7a0573b177a3caa31cc57e6f55f8b371cf5d9166c70fe2e52c9a2"

      define_method(:install) do
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.6/kcl-v0.12.6-linux-amd64.tar.gz"
      sha256 "9ff2c5a37e5e2383f8a980ef451c3ac538e8260039a227fbd46f9ddbe9f49974"
      define_method(:install) do
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.6/kcl-v0.12.6-linux-arm64.tar.gz"
      sha256 "11186b27371d013c09f92ca3cb3efac62a2fe7113ce5fa54eaa6f846c6d1b1f1"
      define_method(:install) do
        bin.install "kcl"
      end
    end
  end
end
