# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcl < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.12.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.7/kcl-v0.12.7-darwin-amd64.tar.gz"
      sha256 "be348eed7e5b93136343e97416c3459d557fbe059a0a0cbe28173d058faaae15"

      define_method(:install) do
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.7/kcl-v0.12.7-darwin-arm64.tar.gz"
      sha256 "f01f00f0f0ab26aa1fea1ff7dca856c9d9df064bd56e1570431e755ac6416abf"

      define_method(:install) do
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.7/kcl-v0.12.7-linux-amd64.tar.gz"
      sha256 "87a13210e1322327b70aa2482f3eaf195b135de6cc0126c40ec29abfeb578174"
      define_method(:install) do
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.7/kcl-v0.12.7-linux-arm64.tar.gz"
      sha256 "3dd3d1bc9f9a177a9e24d1f9c559f1c65f4cf1048dc636f9d8fa031b12807abb"
      define_method(:install) do
        bin.install "kcl"
      end
    end
  end
end
