# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcl < Formula
  desc "KCL Command Line Interface"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.12.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.5/kcl-v0.12.5-darwin-amd64.tar.gz"
      sha256 "9be5d23bd0422644a4c1ee453d4ae6560ebf01bdc33a3c6d8adc9901b96bf127"

      define_method(:install) do
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.5/kcl-v0.12.5-darwin-arm64.tar.gz"
      sha256 "52310743de7343d07db3b6ca1bf1b9ba10aa16a44f90c1d460de9381d5464f7d"

      define_method(:install) do
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.5/kcl-v0.12.5-linux-amd64.tar.gz"
      sha256 "9b46dc661b36c86bca82ccb86d31ca41ca779a48aa6f367a1d19b9fec133e7f9"
      define_method(:install) do
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kcl-lang/cli/releases/download/v0.12.5/kcl-v0.12.5-linux-arm64.tar.gz"
      sha256 "b99d369e50f9525f127587955c9f7b284921f51342cea86de6152fc1ea865f58"
      define_method(:install) do
        bin.install "kcl"
      end
    end
  end
end
